name: Build

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  PRINCIPIA_MSVC: .
  PRINCIPIA_KSP_ASSEMBLIES_VERSION: 1.12.5

jobs:
  build:
    runs-on: self-hosted
    strategy:
        matrix:
          configuration: [Debug, Release]
    steps:
    - name: Checkout source files
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Download KSP assemblies
      run: |
        mkdir -f '..\KSP Assemblies'
        Invoke-WebRequest                   `
          http://principia.mockingbirdnest.com/${{ secrets.PRINCIPIA_KSP_ASSEMBLIES_DIRECTORY}}/KSP%20Assemblies/${{ env.PRINCIPIA_KSP_ASSEMBLIES_VERSION }}.zip `
          -OutFile '..\KSP Assemblies\${{ env.PRINCIPIA_KSP_ASSEMBLIES_VERSION }}.zip'
        Expand-Archive -f '..\KSP Assemblies\${{ env.PRINCIPIA_KSP_ASSEMBLIES_VERSION }}.zip' '..\KSP Assemblies'

    - name: Download abseil artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: abseil-cpp
        directory: Google

    - name: Download benchmark artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: benchmark
        directory: Google

    - name: Download gipfeli artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: gipfeli
        directory: Google

    - name: Download glog artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: glog
        directory: Google

    - name: Download googletest artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: googletest
        directory: Google

    - name: Download protobuf artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: protobuf
        directory: Google

    - name: Download zfp artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: zfp
        directory: 'Third Party'

    - name: Restore ${{ matrix.configuration }}
      uses: mockingbirdnest/actions/windows/restore@main
      with:
        configuration: ${{ matrix.configuration }}
        solution_directory: ${{ env.PRINCIPIA_MSVC }}

#    - name: Rebuild ${{ matrix.configuration }}
#      uses: mockingbirdnest/actions/windows/rebuild@main
#      with:
#        configuration: ${{ matrix.configuration }}
#        solution_directory: ${{ env.PRINCIPIA_MSVC }}

    - name: Test ${{ matrix.configuration }}
      run: |
        Remove-Item -Recurse TestResults
        if ( ${{matrix.configuration}} -eq 'Debug') {
          $granularity = 'Package'
        } else {
          $granularity = 'Test'
        }
        .\parallel_test_runner\bin\Release\parallel_test_runner.exe `
          --granularity:$granularity                                `
          .\${{ matrix.configuration }}\x64

    - name: Pick artifact name
      run: |
        echo "PRINCIPIA_ARTIFACT_NAME=${{ matrix.configuration}}-$(git describe --tags --always --dirty --abbrev=40 --long)" >> $env:GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: principia_${{ env.PRINCIPIA_ARTIFACT_NAME }}
        # The * after GameData is to preserve that directory in the artifact.
        path: ${{ matrix.configuration }}/GameData*

