name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  PRINCIPIA_MSVC: .

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration: [Debug, Release]
    steps:
    - name: Checkout source files
      uses: actions/checkout@v3

    - name: Find MSBuild
      uses: mockingbirdnest/actions/windows/find_msbuild@WF1

    - name: Restore ${{ matrix.configuration }}
      uses: mockingbirdnest/actions/windows/restore@WF1
      with:
        configuration: ${{ matrix.configuration }}
        solution_directory: ${{ env.PRINCIPIA_MSVC }}

    - name: Rebuild ${{ matrix.configuration }}
      uses: mockingbirdnest/actions/windows/rebuild@WF1
      with:
        configuration: ${{ matrix.configuration }}
        solution_directory: ${{ env.PRINCIPIA_MSVC }}

