name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    - name: Rebuild ${{ matrix.configuration }}
      shell: pwsh
      run: |
        $msbuild = &".\find_msbuild.ps1"
        &$msbuild /t:Restore Principia.sln
        &$msbuild /t:"Clean;Build" /m /property:Configuration=${{ matrix.configuration }} Principia.sln
