name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration: [Debug, Release]
    steps:
    - name: Checkout source files
      uses: actions/checkout@v3
    - name: Find MSBuild version
      shell: pwsh
      run: >
        $msbuild = &".\find_msbuild.ps1"
    - name: Restore ${{ matrix.configuration }}
      run: >
        &$msbuild
          /target:Restore
          Principia.sln
          /property:Configuration=${{ matrix.configuration }}
    - name: Rebuild ${{ matrix.configuration }}
      run: >
        &$msbuild
          /target:"Clean;Build"
          /maxCpuCount
          /property:Configuration=${{ matrix.configuration }}
          /property:Platform=x64
          Principia.sln
