name: Check for “remove before flight” tags

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  check-source:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check source tree
      shell: pwsh
      run: |
        ls -Recurse
        | sls ([System.Text.ASCIIEncoding]::new().GetString(
                   [System.Text.Encoding]::GetEncoding(20866).GetBytes(
                       "реможе бефоре флигхт").foreach({$_ -band 0x7F})))
          -CaseSensitive
        | Should -Be @()

  check-pull-request-description:
    runs-on: windows-latest
    steps:
    - name: Check pull request
      shell: pwsh
      run: |
        echo $github.event
